### ISSUE TITLE
addHexPrefix 

### ISSUE THREAD

**Issue by wanderer** [ethjs/ethjs-util#1]
What do you think about adding [addHexPrefix](https://github.com/ethereumjs/ethereumjs-util/blob/d03528e7da885539cad141c99ea5b88829f73e72/index.js#L502-L508) ? Since we have stripHexPrefix and isHexPrefix here it would be nice if we could move addHexPrefix from ethereumjs-util to here also

**Comment by SilentCicero** [comment]
@wanderer will add, should I make a PR?

**Comment by wanderer** [comment]
@SilentCicero done https://github.com/ethjs/ethjs-util/pull/3

**Comment by SilentCicero** [comment]
Now added, thanks @wanderer sorry it took so long. Travelling.
