### ISSUE TITLE
intToHex encodes values incorrectly

### ISSUE THREAD

**Issue by DaveAppleton** [ethjs/ethjs-util#6]
# ethjs-util

Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/ethjs/ethjs-util/blob/master/.github/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

**Before opening a new issue, you may find an answer in already closed issues**:
https://github.com/ethjs/ethjs-util/issues?q=is%3Aissue+is%3Aclosed

## Issue Type

- [X ] Bug (https://github.com/ethjs/ethjs-util/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/ethjs/ethjs-util/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

Ethereum declares that hex values should be encoded compactly. 

`0x0`
`0x1`
`0x11`

are all valid

`0x`
`0x00`
`0x01`

are not

This causes problems when this library is used in products that talk to software that adheres more strictly to the standard - e.g. go-ethereum linked code talking to ganache.

This stems from 

https://github.com/ethjs/ethjs-util/blob/master/src/index.js#L4-L33

(Add images if possible)

## Steps to reproduce

(Add link to a demo on https://jsfiddle.net or similar if possible)

# Versions

- Node/NPM:
- Browser:

**Comment by SilentCicero** [comment]
Can you submit a Pr, looks like we have padding set by default (which your right would cause problems)

**Comment by DaveAppleton** [comment]
Is there any case when it **would** be needed?

**Comment by DaveAppleton** [comment]
PR submitted...

**Comment by SilentCicero** [comment]
Sorry, will try and merge today. I think so the padding was added for log indexes which require padding. I'll see what we can do to address that and where else the padding is used.

**Comment by SilentCicero** [comment]
Had a rough day today, will take a look tomorrow. Apologies

**Comment by GoldenDave** [comment]
No movement? It makes ganche unusable with non truffle clients...

**Comment by SilentCicero** [comment]
Where exactly does it make it unusable? I know, it's been a crazy month, will try and merge or fix today.

**Comment by SilentCicero** [comment]
@GoldenDave thanks so much, pushed in Version 1.5 on NPM.
